### ISSUE TITLE
Notification Support

### ISSUE THREAD

**Issue by irgendwr** [multiplay/go-ts3#17]
Hi, quick question: Does this package support notification handling?
Can you provide an example on how to receive notifications?

Thanks!

**Comment by irgendwr** [comment]
@stevenh Would you be open to a PR that adds support for notifications?
I'll have to rewrite the way that scanning is done though (an approach similar to [Darfk/ts3](https://github.com/Darfk/ts3/blob/master/ts3.go#L100) might make sense).

**Comment by stevenh** [comment]
sure, PR away :)

**Comment by irgendwr** [comment]
One thing I noticed:
Why does ExecCmd and Ecec return a string array? The ServerQuery never returns more than one line as far as I know (ignoring the error message and notify messages of course).
Would you prefer...
A: The func's return an array even though it always contains only one element, or
B: The func's return a string?
The problem with B is that it would break backwards compatibility, even though it makes more sense imho.

**Comment by stevenh** [comment]
IIRC we made it due to some command not returning any responses other than the OK / Error, that and it gave use flexibility in case there where multiple line responses in the future.

Off the top of my head having a method to enable notifications that returns a channel the caller can then read any notifications off might be a good way to go.

It may well be hard to intermixing standard commands with notifications work cleanly, not used them, so it may be easier to recommend a separate client command for notifications?

**Comment by irgendwr** [comment]
> IIRC we made it due to some command not returning any responses other than the OK / Error, that and it gave use flexibility in case there where multiple line responses in the future.

That makes sense, I'll leave it that way then.

> having a method to enable notifications that returns a channel the caller can then read any notifications off might be a good way to go.

I'll add a func to register events and one to set an event handler. I personally prefer a handler func over a channel but this could easily be changed if a channel makes more sense.

> It may well be hard to intermixing standard commands with notifications work cleanly, not used them, so it may be easier to recommend a separate client command for notifications?

Yeah maybe but I don't really like the thought of having multiple clients for just one program and I think that I solved the problem anyway so it should also work with one client.
